apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistentvolume
  namespace: muhannadsinan-tawazun
  labels:
    type: local
    name: muhannadsinan
spec:
  storageClassName: manual
  capacity:
    storage: "500Mi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"