apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-deployment
  namespace: muhannadsinan-tawazun
  labels:
    app: tawazun
    name: muhannadsinan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
  template:
    metadata:
      labels:
        app: tawazun
    spec:
      containers:
        - image: mohanadsinan/tawazun:latest
          name: tawazun
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: mysql-service
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: tawazun
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: DevOps2022
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "2"
          startupProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10