apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistentvolume
  namespace: muhannadsinan-tawazun
  labels:
    type: local
    name: muhannadsinan
spec:
  storageClassName: manual
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
      volumeID: "vol-0e0928c2f03c580e8"
      fsType: ext4