apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: muhannadsinan-tawazun
  labels:
    name: muhannadsinan
spec:
 selector:
    app: mysql
 type: ClusterIP
 ports:
    - protocol: TCP
      port: 3306